/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ntuhxxihvscwtdilxxma"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dWh4eGlodnNjd3RkaWx4eG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNzYzNzksImV4cCI6MjA4Njc1MjM3OX0.t-IQGAVR3l7tvWDw5GICnXyKusSOCxauRqDs0q-vCvA"